kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c
  - linuxkit/runc:v0.8
  - linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
services:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
