kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:1a0c6b624708b5a9e58b9a608a9ce3164e7b2908
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:2e7e59b8af98a1cec834dc9fe7aba271bf4b0a41
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
services:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
