kernel:
  image: "linuxkitprojects/kernel-memorizer:4.10_dbg"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:v0.7
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
