kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:4f6508f4f35b134dda3807bb5d75c117c193a86a
  - linuxkit/runc:v0.8
  - linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:v0.8
    command: ["/usr/bin/format", "/dev/sda"]
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/dev/sda1", "/var/external"]
  - name: loop
    image: linuxkit/losetup:v0.8
    command: ["/usr/bin/loopy", "--create", "/var/external/storage_file"]
  - name: dm-crypt
    image: linuxkit/dm-crypt:v0.8
    command: ["/usr/bin/crypto", "crypt_loop_dev", "/dev/loop0"]
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/dev/mapper/crypt_loop_dev", "/var/secure_storage"]
  - name: bbox
    image: busybox
    command: ["sh", "-c", "echo 'secret things' >/var/secure_storage/secrets"]
    binds:
      - /var:/var
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
files:
  - path: etc/dm-crypt/key
    # the below key is just to keep the example self-contained
    # !!! provide a proper key for production use here !!!
    contents: "abcdefghijklmnopqrstuvwxyz123456"
trust:
  org:
    - linuxkit
