kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: node_exporter
    image: linuxkit/node_exporter:v0.8
trust:
  org:
    - linuxkit
