kernel:
  image: linuxkit/kernel:4.19.47
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:v0.7
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: node_exporter
    image: linuxkit/node_exporter:v0.7
trust:
  org:
    - linuxkit
