kernel:
  image: linuxkit/kernel:4.19.51
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:1d8e0532ca588c5ad0d9ca6038349a70bb7ac626
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:751de142273e1b5d2d247d2832d654ab92e907bc
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:02c555b50cd1887aa628836662d2eec54c0d7e81
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: node_exporter
    image: linuxkit/node_exporter:v0.7
trust:
  org:
    - linuxkit
