kernel:
  image: linuxkit/kernel:4.19.51
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:1a0c6b624708b5a9e58b9a608a9ce3164e7b2908
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:2e7e59b8af98a1cec834dc9fe7aba271bf4b0a41
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.7
    command: ["/usr/bin/metadata", "openstack"]
services:
  - name: rngd
    image: linuxkit/rngd:02c555b50cd1887aa628836662d2eec54c0d7e81
  - name: sshd
    image: linuxkit/sshd:v0.7
    binds:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
trust:
  org:
    - linuxkit
    - library
