kernel:
  image: linuxkit/kernel:4.19.46
  cmdline: "console=tty0"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:v0.7
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
trust:
  org:
    - linuxkit
    - library
